export enum ProjectActionTypeKeys {
    ADD_PROJECT = 'ADD_PROJECT',
    SET_PROJECTS = 'SET_PROJECTS',
    CLOSE_MODAL = 'CLOSE_MODAL',
    OPEN_MODAL = 'OPEN_MODAL',
    REMOVE_PROJECT = 'REMOVE_PROJECT',
    UPDATE_PROJECT = 'UPDATE_PROJECT'
};